expanded tabs to 4 whitespace for consistency

diff --git a/gitflux-common b/gitflux-common
--- a/gitflux-common
+++ b/gitflux-common
@@ -55,13 +55,13 @@ warn() { echo "$@" >&2; }
 die() { warn "$@"; exit 1; }
 
 escape() {
-	echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
+    echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
 }
 
 # set logic
 has() {
-	local item=$1; shift
-	echo " $@ " | grep -q " $(escape $item) "
+    local item=$1; shift
+    echo " $@ " | grep -q " $(escape $item) "
 }
 
 # basic math
@@ -86,37 +86,37 @@ git_all_branches() { ( git branch --no-color; git branch -r --no-color) | sed 's
 git_all_tags() { git tag; }
 
 git_current_branch() {
-	git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
+    git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
 }
 
 git_is_clean_working_tree() {
-	if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
-		return 1
-	elif ! git diff-index --cached --quiet --ignore-submodules HEAD --; then
-		return 2
-	else
-		return 0
-	fi
+    if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
+        return 1
+    elif ! git diff-index --cached --quiet --ignore-submodules HEAD --; then
+        return 2
+    else
+        return 0
+    fi
 }
 
 git_repo_is_headless() {
-	! git rev-parse --quiet --verify HEAD >/dev/null 2>&1
+    ! git rev-parse --quiet --verify HEAD >/dev/null 2>&1
 }
 
 git_local_branch_exists() {
-	has $1 $(git_local_branches)
+    has $1 $(git_local_branches)
 }
 
 git_remote_branch_exists() {
-	has $1 $(git_remote_branches)
+    has $1 $(git_remote_branches)
 }
 
 git_branch_exists() {
-	has $1 $(git_all_branches)
+    has $1 $(git_all_branches)
 }
 
 git_tag_exists() {
-	has $1 $(git_all_tags)
+    has $1 $(git_all_tags)
 }
 
 #
@@ -132,22 +132,22 @@ git_tag_exists() {
 # 4    There is no merge base, i.e. the branches have no common ancestors
 #
 git_compare_branches() {
-	local commit1=$(git rev-parse "$1")
-	local commit2=$(git rev-parse "$2")
-	if [ "$commit1" != "$commit2" ]; then
-		local base=$(git merge-base "$commit1" "$commit2")
-		if [ $? -ne 0 ]; then
-			return 4
-		elif [ "$commit1" = "$base" ]; then
-			return 1
-		elif [ "$commit2" = "$base" ]; then
-			return 2
-		else
-			return 3
-		fi
-	else
-		return 0
-	fi
+    local commit1=$(git rev-parse "$1")
+    local commit2=$(git rev-parse "$2")
+    if [ "$commit1" != "$commit2" ]; then
+        local base=$(git merge-base "$commit1" "$commit2")
+        if [ $? -ne 0 ]; then
+            return 4
+        elif [ "$commit1" = "$base" ]; then
+            return 1
+        elif [ "$commit2" = "$base" ]; then
+            return 2
+        else
+            return 3
+        fi
+    else
+        return 0
+    fi
 }
 
 #
@@ -156,10 +156,10 @@ git_compare_branches() {
 # Checks whether branch $1 is succesfully merged into $2
 #
 git_is_branch_merged_into() {
-	local subject=$1
-	local base=$2
-	local all_merges="$(git branch --no-color --contains $subject | sed 's/^[* ] //')"
-	has $base $all_merges
+    local subject=$1
+    local base=$2
+    local all_merges="$(git branch --no-color --contains $subject | sed 's/^[* ] //')"
+    has $base $all_merges
 }
 
 #
@@ -168,37 +168,37 @@ git_is_branch_merged_into() {
 
 # check if this repo has been inited for gitflow
 gitflow_has_master_configured() {
-	local master=$(git config --get gitflow.branch.master)
-	[ "$master" != "" ] && git_local_branch_exists "$master"
+    local master=$(git config --get gitflow.branch.master)
+    [ "$master" != "" ] && git_local_branch_exists "$master"
 }
 
 gitflow_has_develop_configured() {
-	local develop=$(git config --get gitflow.branch.develop)
-	[ "$develop" != "" ] && git_local_branch_exists "$develop"
+    local develop=$(git config --get gitflow.branch.develop)
+    [ "$develop" != "" ] && git_local_branch_exists "$develop"
 }
 
 gitflow_has_prefixes_configured() {
-	git config --get gitflow.prefix.feature >/dev/null 2>&1     && \
-	git config --get gitflow.prefix.release >/dev/null 2>&1     && \
-	git config --get gitflow.prefix.hotfix >/dev/null 2>&1      && \
-	git config --get gitflow.prefix.support >/dev/null 2>&1     && \
-	git config --get gitflow.prefix.versiontag >/dev/null 2>&1
+    git config --get gitflow.prefix.feature >/dev/null 2>&1     && \
+    git config --get gitflow.prefix.release >/dev/null 2>&1     && \
+    git config --get gitflow.prefix.hotfix >/dev/null 2>&1      && \
+    git config --get gitflow.prefix.support >/dev/null 2>&1     && \
+    git config --get gitflow.prefix.versiontag >/dev/null 2>&1
 }
 
 gitflow_is_initialized() {
-	gitflow_has_master_configured                    && \
-	gitflow_has_develop_configured                   && \
-	[ "$(git config --get gitflow.branch.master)" !=    \
-	  "$(git config --get gitflow.branch.develop)" ] && \
-	gitflow_has_prefixes_configured
+    gitflow_has_master_configured                    && \
+    gitflow_has_develop_configured                   && \
+    [ "$(git config --get gitflow.branch.master)" !=    \
+      "$(git config --get gitflow.branch.develop)" ] && \
+    gitflow_has_prefixes_configured
 }
 
 # loading settings that can be overridden using git config
 gitflow_load_settings() {
-	export DOT_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
-	export MASTER_BRANCH=$(git config --get gitflow.branch.master)
-	export DEVELOP_BRANCH=$(git config --get gitflow.branch.develop)
-	export ORIGIN=$(git config --get gitflow.origin || echo origin)
+    export DOT_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
+    export MASTER_BRANCH=$(git config --get gitflow.branch.master)
+    export DEVELOP_BRANCH=$(git config --get gitflow.branch.develop)
+    export ORIGIN=$(git config --get gitflow.origin || echo origin)
 }
 
 #
@@ -218,36 +218,36 @@ gitflow_load_settings() {
 # 2: Multiple matches found. These matches are written to stderr
 #
 gitflow_resolve_nameprefix() {
-	local name=$1
-	local prefix=$2
-	local matches
-	local num_matches
+    local name=$1
+    local prefix=$2
+    local matches
+    local num_matches
 
-	# first, check if there is a perfect match
-	if git_local_branch_exists "$prefix$name"; then
-		echo "$name"
-		return 0
-	fi
+    # first, check if there is a perfect match
+    if git_local_branch_exists "$prefix$name"; then
+        echo "$name"
+        return 0
+    fi
 
-	matches=$(echo "$(git_local_branches)" | grep "^$(escape "$prefix$name")")
-	num_matches=$(echo "$matches" | wc -l)
-	if [ -z "$matches" ]; then
-		# no prefix match, so take it literally
-		warn "No branch matches prefix '$name'"
-		return 1
-	else
-		if [ $num_matches -eq 1 ]; then
-			echo "${matches#$prefix}"
-			return 0
-		else
-			# multiple matches, cannot decide
-			warn "Multiple branches match prefix '$name':"
-			for match in $matches; do
-				warn "- $match"
-			done
-			return 2
-		fi
-	fi
+    matches=$(echo "$(git_local_branches)" | grep "^$(escape "$prefix$name")")
+    num_matches=$(echo "$matches" | wc -l)
+    if [ -z "$matches" ]; then
+        # no prefix match, so take it literally
+        warn "No branch matches prefix '$name'"
+        return 1
+    else
+        if [ $num_matches -eq 1 ]; then
+            echo "${matches#$prefix}"
+            return 0
+        else
+            # multiple matches, cannot decide
+            warn "Multiple branches match prefix '$name':"
+            for match in $matches; do
+                warn "- $match"
+            done
+            return 2
+        fi
+    fi
 }
 
 #
@@ -255,74 +255,74 @@ gitflow_resolve_nameprefix() {
 #
 
 require_git_repo() {
-	if ! git rev-parse --git-dir >/dev/null 2>&1; then
-		die "fatal: Not a git repository"
-	fi
+    if ! git rev-parse --git-dir >/dev/null 2>&1; then
+        die "fatal: Not a git repository"
+    fi
 }
 
 require_gitflow_initialized() {
-	if ! gitflow_is_initialized; then
-		die "fatal: Not a gitflow-enabled repo yet. Please run \"git flow init\" first."
-	fi
+    if ! gitflow_is_initialized; then
+        die "fatal: Not a gitflow-enabled repo yet. Please run \"git flow init\" first."
+    fi
 }
 
 require_clean_working_tree() {
-	git_is_clean_working_tree
-	local result=$?
-	if [ $result -eq 1 ]; then
-		die "fatal: Working tree contains unstaged changes. Aborting."
-	fi
-	if [ $result -eq 2 ]; then
-		die "fatal: Index contains uncommited changes. Aborting."
-	fi
+    git_is_clean_working_tree
+    local result=$?
+    if [ $result -eq 1 ]; then
+        die "fatal: Working tree contains unstaged changes. Aborting."
+    fi
+    if [ $result -eq 2 ]; then
+        die "fatal: Index contains uncommited changes. Aborting."
+    fi
 }
 
 require_local_branch() {
-	if ! git_local_branch_exists $1; then
-		die "fatal: Local branch '$1' does not exist and is required."
-	fi
+    if ! git_local_branch_exists $1; then
+        die "fatal: Local branch '$1' does not exist and is required."
+    fi
 }
 
 require_remote_branch() {
-	if ! has $1 $(git_remote_branches); then
-		die "Remote branch '$1' does not exist and is required."
-	fi
+    if ! has $1 $(git_remote_branches); then
+        die "Remote branch '$1' does not exist and is required."
+    fi
 }
 
 require_branch() {
-	if ! has $1 $(git_all_branches); then
-		die "Branch '$1' does not exist and is required."
-	fi
+    if ! has $1 $(git_all_branches); then
+        die "Branch '$1' does not exist and is required."
+    fi
 }
 
 require_branch_absent() {
-	if has $1 $(git_all_branches); then
-		die "Branch '$1' already exists. Pick another name."
-	fi
+    if has $1 $(git_all_branches); then
+        die "Branch '$1' already exists. Pick another name."
+    fi
 }
 
 require_tag_absent() {
-	for tag in $(git_all_tags); do
-		if [ "$1" = "$tag" ]; then
-			die "Tag '$1' already exists. Pick another name."
-		fi
-	done
+    for tag in $(git_all_tags); do
+        if [ "$1" = "$tag" ]; then
+            die "Tag '$1' already exists. Pick another name."
+        fi
+    done
 }
 
 require_branches_equal() {
-	require_local_branch "$1"
-	require_remote_branch "$2"
-	git_compare_branches "$1" "$2"
-	local status=$?
-	if [ $status -gt 0 ]; then
-		warn "Branches '$1' and '$2' have diverged."
-		if [ $status -eq 1 ]; then
-			die "And branch '$1' may be fast-forwarded."
-		elif [ $status -eq 2 ]; then
-			# Warn here, since there is no harm in being ahead
-			warn "And local branch '$1' is ahead of '$2'."
-		else
-			die "Branches need merging first."
-		fi
-	fi
+    require_local_branch "$1"
+    require_remote_branch "$2"
+    git_compare_branches "$1" "$2"
+    local status=$?
+    if [ $status -gt 0 ]; then
+        warn "Branches '$1' and '$2' have diverged."
+        if [ $status -eq 1 ]; then
+            die "And branch '$1' may be fast-forwarded."
+        elif [ $status -eq 2 ]; then
+            # Warn here, since there is no harm in being ahead
+            warn "And local branch '$1' is ahead of '$2'."
+        else
+            die "Branches need merging first."
+        fi
+    fi
 }
